### ISSUE TITLE
zlib.error: Error -3 while decompressing data: incorrect header check

### ISSUE THREAD

**Issue by alixleger** [saleweaver/python-amazon-sp-api#1076] opened 2023-06-21 07:17 UTC
**Describe the bug**
Since 21/06/23 01:00 AM UTC, we cannot get feed result documents of json listings feeds.

Traceback:

```
return service.get_feed_result_document(document_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/mpinfestor/lib/python3.11/site-packages/sp_api/base/helpers.py", line 20, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/mpinfestor/lib/python3.11/site-packages/sp_api/api/feeds/feeds.py", line 233, in get_feed_result_document
    return zlib.decompress(bytearray(content), 15 + 32).decode(encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
zlib.error: Error -3 while decompressing data: incorrect header check
Failed: NonZeroResultCode: [ssh-exec] Result code: 1
``` 

**To Reproduce**

* Create and submit a json listings feed
* Get the feed id
* Call the Feeds.get_feed_result_document(feed_id) operation

**Desktop (please complete the following information):**

 - OS: `Linux 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux`

**Comment by wolendranh** [comment] 2023-06-21 14:14
Hi! I am experiencing same issue for Reports api. Looks like indeed amazon issue

**Comment by twistedFantasy** [comment] 2023-06-21 14:18
We also start facing the same issue using [Amazon Selling Partner **Reports** API](https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference).

This error is raised when we try to download already successfully completed report and call `get_report_document(...)`.
```
from sp_api.api import Reports

Reports(marketplace=marketplace, credentials=credentials).get_report_document(reportDocumentId=document_id, download=True, file=path, decrypt=True)


error: Error -3 while decompressing data: incorrect header check
Traceback (most recent call last):
    .....
    Reports(marketplace=marketplace, credentials=credentials).get_report_document(reportDocumentId=document_id, download=True, file=path, decrypt=True)
  File "/usr/local/lib/python3.8/dist-packages/sp_api/base/helpers.py", line 19, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sp_api/api/reports/reports.py", line 369, in get_report_document
    document = zlib.decompress(bytearray(document), 15 + 32)
zlib.error: Error -3 while decompressing data: incorrect header check
```

Issue is reproducible for 2 types of DAILY reports:
1. `ReportType.GET_VENDOR_INVENTORY_REPORT` 
2. `ReportType.GET_VENDOR_SALES_REPORT`

**Comment by saleweaver** [comment] 2023-06-21 14:19
Let's wait a bit; hopefully it resolves itself

**Comment by wolendranh** [comment] 2023-06-21 14:30
hi! 
I created [issue](https://github.com/amzn/selling-partner-api-docs/issues/3200) on SP API documentation report. Please add comments there so we get attention from Amazon.

**Comment by alixleger** [comment] 2023-06-21 14:41
> hi! I created [issue](https://github.com/amzn/selling-partner-api-docs/issues/3200) on SP API documentation report. Please add comments there so we get attention from Amazon.

good idea I've also created a case on Developper Support

**Comment by rijumone** [comment] 2023-06-22 07:09
Hi, downgrading to `0.18.0` version of the SDK is resolving the issue.

**Comment by saleweaver** [comment] 2023-06-22 07:11
> Hi, downgrading to `0.18.0` version of the SDK is resolving the issue.

Then I'd say a simple reinstall of latest does the fix as well. There weren't any changes to this part that I'm aware of

**Comment by tmechsner** [comment] 2023-06-22 07:13
> Hi, downgrading to `0.18.0` version of the SDK is resolving the issue.

Doesn't work for us. We were on 0.18.0. already - having this issue though.

**Comment by rijumone** [comment] 2023-06-22 07:15
> > Hi, downgrading to `0.18.0` version of the SDK is resolving the issue.
> 
> Then I'd say a simple reinstall of latest does the fix as well. There weren't any changes to this part that I'm aware of

Confirmed, doing a `pip install python-amazon-sp-api-0.18.4` is working for me. But probably because I have been trying all versions of the SDK, installing and uninstalling them. 
Doing a `pip install --upgrade python-amazon-sp-api` might or might not work. Checking.

**Comment by rijumone** [comment] 2023-06-22 07:24
Downgrading to `0.18.0` or reinstalling `0.18.4` is working for `GET_VENDOR_SALES_REPORT` but not for `GET_V2_SELLER_PERFORMANCE_REPORT`.

**Comment by ssuhre** [comment] 2023-06-22 07:37
Reinstalling, or rather, rebuilding our container image with updated dependencies had no effect. We still get the error.

**Comment by wolendranh** [comment] 2023-06-22 10:55
it is Amazon change and I don't think it has anything to do with package version. You can inherit Reports class from library and change method that downloads report document to skip uncompress or wrap it into try except as temporary fix. 

But we should receive some kind of update from Amazon if this change is permanent or if this is bug. And then act based on that.

**Comment by wolendranh** [comment] 2023-06-22 11:03
Something like this can be temporary used. NOTE - this is temporary, until we get proper communication. Also you can check if file is really GZIP to have more granular control.
```
class CustomReport(Reports):

	@sp_endpoint('/reports/2021-06-30/documents/{}', method='GET')
	def get_report_document(self, reportDocumentId, download: bool = False, file=None,
							character_code: str = 'iso-8859-1', **kwargs) -> ApiResponse:
		res = self._request(fill_query_params(kwargs.pop('path'), reportDocumentId), add_marketplace=False)
		if download or file or ('decrypt' in kwargs and kwargs['decrypt']):
			document = requests.get(res.payload.get('url')).content
			if 'compressionAlgorithm' in res.payload:
				# FIXME: this is temporary fix for issue with compression from Amazon.
				try:
					document = zlib.decompress(bytearray(document), 15 + 32)
				except Exception as e:
					document = document

			if character_code:
				document = document.decode(character_code)
			if download:
				res.payload.update({
					'document': document
				})
			if file:
				self._handle_file(file, document, character_code)
		return res

**Comment by Paul-J-Barrett** [comment] 2023-06-22 19:26
I made the above changes and created a pull request. We are using it in some lambda layers for aws which caused a few deployment issues, because we use the serverless framework. 

I finally got it uploaded and just tested it. The change does seem to fix the issue, appears that Amazon either made a server change or api change that is not encrypting file. 

Hopefully they didn't change the fields of the files as well.

**Comment by saleweaver** [comment] 2023-06-22 19:27
👋 
Can you please put a new version to the version file and I'll merge right away

**Comment by Paul-J-Barrett** [comment] 2023-06-22 20:03
I created another pull request with version minor incremented. Hope that is what you wanted.

**Comment by wolendranh** [comment] 2023-06-22 22:53
@saleweaver @Paul-J-Barrett 
Hi! according to comment in SP API docs [issue](https://github.com/amzn/selling-partner-api-docs/issues/3200#issuecomment-1603406576) bug is now resolved. So I am not sure if change into package is required.

**Comment by Paul-J-Barrett** [comment] 2023-06-23 14:13
I prefer to have the logic there. Loosing all sales reporting for our brand managers makes IT look bad. I would leave it. It causes no harm to make sure there is no error.

**Closed** 2023-06-23 19:16 UTC
Labels: bug
