### ISSUE TITLE
def get_product_fees_estimate(self, estimate_requests: list[dict]) -> ApiResponse:

### ISSUE THREAD

**Issue by cnr91** [saleweaver/python-amazon-sp-api#716] opened 2022-08-31 14:58 UTC
I'm testing it for the first time today. I am getting this error even though I have everything set up correctly.

What is the reason for this error?

**File "D:\anaconda3\lib\site-packages\sp_api\api\product_fees\product_fees.py", line 99, in ProductFees
    def get_product_fees_estimate(self, estimate_requests: list[dict]) -> ApiResponse:
TypeError: 'type' object is not subscriptable**

```
from sp_api.base import Marketplaces
from sp_api.api import Orders

credentials = dict(
    refresh_token='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',  # From Seller central under Authorise -> Refresh Token
    lwa_app_id='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',  # From Seller Central, named CLIENT IDENTIFIER on website.
    lwa_client_secret='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',  # From Seller Central, named CLIENT SECRET on website.
    aws_access_key='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',  # From AWS IAM Setup
    aws_secret_key='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',  # From AWS IAM Setup
    role_arn='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'  #arn:aws:iam::1234567890:role/SellingPartnerAPIRole
)

order_client = Orders(credentials=credentials, marketplace=Marketplaces.AU)
order = order_client.get_order('111-4412524-0850212')
print(order) # `order` is an `ApiResponse`
print(order.payload) # `payload` contains the original response
```

Thank you

**Comment by domdellumich** [comment] 2022-09-01 08:31
For what it's worth, simply deleting the offending line in the init file resolved the issue as my code doesn't use this aspect in particular.

**Comment by Lars147** [comment] 2022-09-02 11:12
This is issue is already resolved in https://github.com/saleweaver/python-amazon-sp-api/pull/717. Please pull from main to get it working or ask the developers to release a new version.

**Comment by domdellumich** [comment] 2022-09-03 02:08
No it was not resolved in #717. A simple Google Colab notebook shows the issue is still prevalent. #723 is the proper adjustment. List[dic] is just a comment describing a representation of what the list would contain - it is not proper Python code. Modifying this statement (as seen in #723) is necessary for the library to function properly.

**Comment by winbyai** [comment] 2022-09-03 02:46
use python-amazon-sp-api==0.15.0. It works well.

**Comment by domdellumich** [comment] 2022-09-03 02:53
It does work well, but that's because it doesn't have the bug that #723 is meant to fix :/

**Comment by Lars147** [comment] 2022-09-03 03:36
> No it was not resolved in #717. A simple Google Colab notebook shows the issue is still prevalent. #723 is the proper adjustment. List[dic] is just a comment describing a representation of what the list would contain - it is not proper Python code. Modifying this statement (as seen in #723) is necessary for the library to function properly. @saleweaver mind reviewing the CL?

Please, see my comment on your PR. I would like to help you here.
Are you installing from pip or GitHub directly?

**Comment by domdellumich** [comment] 2022-09-03 03:52
I see now Lars, seems as though you're right and a new version needs to be pushed out accordingly.

**Comment by lizdeika** [comment] 2022-09-06 13:45
this broke a lot of things in aws MWAA which uses python 3.7

**Comment by saleweaver** [comment] 2022-09-09 13:06
https://github.com/saleweaver/python-amazon-sp-api/releases/tag/v0.17.1

**Closed by saleweaver** 2022-09-09 13:06 UTC
Labels: bug
